# Generated by Django 6.0.3 on 2026-06-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ball',
            field=models.IntegerField(default=0),
        ),
    ]
